name: Build artifacts
description: Restores the build artifacts from the workflow cache.

runs:
  using: composite
  steps:
    - name: Restore build artifacts from the workflow cache
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        # A cache miss should never occur, as the `ci.yml` workflow should have built the project prior to this step.
        #
        # CAUTION: The cache key originates from the `ci.yml` workflow.
        key: can-build-project-${{ runner.os }}-sha256:${{ hashFiles('src/**/*', '!src/**/*.testdata.*', '!src/**/*.tests.*', '*.ts', '.env', 'mise.toml', 'pnpm-lock.yaml', 'tsconfig.json') }}
        path: dist/
        fail-on-cache-miss: true
