# Adjust the settings for the Yarn package manager.
#
# Read more:
# https://yarnpkg.com/configuration/yarnrc

# Use exact semver ranges to reduce churn in the zero-install cache.
defaultSemverRangePrefix: ""

# Use the zero-install cache to:
# - Significantly reduce the need for 'yarn install'.
# - Speed up workflows in GitHub Actions.
# - Have a mirror of all dependencies, in case the npm registry is unavailable.
enableGlobalCache: false

# Store binary dependencies for multiple platforms to reduce churn in the zero-install cache.
supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - x64
    - arm64
