name: Validate commit messages in pull requests
description: Fails with a non-zero exit code if a commit message in a pull request is deemed invalid to remind developers to keep the commit history healthy by rebasing interactively before merging the pull request.
author: Steffen Diswal
inputs:
  github-token:
    description: The GitHub token that lets the action list the commits in the pull request.
    required: true
  rules:
    description: A comma-separated list of the rules to enforce.
    required: true
  imperative-subject-lines--whitelist:
    description: A comma-separated list of additional words to be accepted by `imperative-subject-lines`.
    required: false
  issue-references-in-subject-lines--allowed-positions:
    description: A comma-separated list of positions where the issue reference is allowed to appear in the subject line. Valid positions are `as-prefix` and `as-suffix`. It is enforced by `issue-reference-in-subject-lines`.
    required: false
    default: as-prefix,as-suffix
  issue-references-in-subject-lines--patterns:
    description: A space-separated list of regular expressions for issue references, e.g. `#[1-9][0-9]*` for GitHub issues or `ABC-[1-9][0-9]*` for Jira or YouTrack issues in a project named `ABC`. It is required for `issue-reference-in-subject-lines`.
    required: false
    default: ^\b$
  limit-line-lengths--max-body-line-characters:
    description: The maximum number of characters allowed per line in the commit message body. It is enforced by `limit-line-lengths`. Use `0` to disable the limit on body lines.
    required: false
    default: "72"
  limit-line-lengths--max-subject-line-characters:
    description: The maximum number of characters allowed in the subject line. It is enforced by `limit-line-lengths`. Use `0` to disable the limit on subject lines.
    required: false
    default: "50"
  no-squash-commits--disallowed-prefixes:
    description: A comma-separated list of subject line prefixes to be rejected by `no-squash-commits`.
    required: false
    default: amend!,fixup!,squash!
  no-trailing-punctuation-in-subject-lines--whitelist:
    description: A space-separated list of punctuation marks to be ignored by `no-trailing-punctuation-in-subject-lines`.
    required: false
runs:
  using: node16
  main: release/index.cjs
