= Contribution Guidelines
:experimental:
:source-highlighter: highlight.js

Thank you for investing your time in contributing to our project!
If you are a first-time contributor to this project, please take a look at the <<get_started>> section 😀

CAUTION: All commands in this README document are to be executed from the project root directory (where this document resides).

[[get_started]]
== Get Started
This project uses the https://yarnpkg.com/features/zero-installs[zero-install feature] of the Yarn package manager.
Upon cloning the Git repository, the `.yarn/cache` directory already contains a cache of the third-party dependencies, effectively replacing the usual `node_modules` directory.

=== Install Node.js and Yarn
* *macOS* and *Linux* users should install https://nodejs.org/en[Node.js] via https://github.com/nvm-sh/nvm[Node Version Manager] and opt for https://yarnpkg.com/getting-started/install[Yarn] via https://nodejs.org/api/corepack.html[Corepack]:
+
[source,shell]
----
curl https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
source ~/.bashrc
nvm install --lts
corepack enable yarn
yarn run setup
----

* *Windows* users should install https://nodejs.org/en[Node.js] via https://github.com/microsoft/winget-cli[Windows Package Manager] and install https://yarnpkg.com/getting-started/install[Yarn] via npm (which is actually a workaround until Corepack supports Windows):
+
[source,shell]
----
winget install OpenJS.NodeJS.LTS
npm install --global yarn
yarn run setup
----

=== Install Act
* *macOS* and *Linux* users should install https://github.com/nektos/act[Act] via https://brew.sh[Homebrew]:
+
[source,shell]
----
brew install act
----
* *Windows* users should install https://github.com/nektos/act[Act] via https://github.com/microsoft/winget-cli[Windows Package Manager]:
+
[source,shell]
----
winget install nektos.act
----

=== Prepare Git
. Generate an SSH key with the *Ed25519* algorithm, for example using https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent[ssh-keygen] or https://developer.1password.com/docs/ssh/manage-keys[1Password], and add it to the SSH agent on your computer.
If you already have an SSH key on your computer, you may skip this step.
+
[source,shell,subs="+quotes,+replacements"]
----
ssh-keygen -t ed25519 -f "$HOME/.ssh/**_<my-ssh-key>_**"
ssh-add ~/.ssh/<my-ssh-key>
----

* *Windows* users must instruct Git to use https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_overview[Microsoft OpenSSH] as the SSH agent:
+
[source,shell]
----
git config --global core.sshCommand "C:/Windows/System32/OpenSSH/ssh.exe"
----

. Grab the **_public_** key.
It appears like `ssh-ed25519 AAAAC3(...)`.
+
[source,shell,subs="+quotes,+replacements"]
----
cat ~/.ssh/**_<my-ssh-key>_**.pub
----

. Register the public key in https://github.com/settings/keys[GitHub] as a signing key.

. Obtain your noreply email address on https://github.com/settings/emails[GitHub].
It appears like `**_<id+username>_**@users.noreply.github.com`.

. Declare your identity within the scope of this repository and use the public key to sign your commits:
+
[source,shell,subs="+quotes,+replacements"]
----
git config user.name "**_<FirstName> <LastName>_**"
git config user.email "**_<id+username>_**@users.noreply.github.com"
git config user.signingkey "ssh-ed25519 AAAAC3**_<PublicKey>_**"
git config gpg.format "ssh"
git config commit.gpgsign "true"
git config tag.gpgsign "true"
----

=== Prepare Your IDE
* *IntelliJ IDEA* (and *WebStorm*) users should open the project directory:
+
[source,shell]
----
idea .
----

. Install these plugins (follow the popup message, or go to menu:File[Settings > Plugins]):
** https://plugins.jetbrains.com/plugin/7391-asciidoc[AsciiDoc]
** https://plugins.jetbrains.com/plugin/10456-prettier[Prettier]

. Go to menu:File[Settings > Languages & Frameworks > Node.js].
Select the appropriate Node.js interpreter and enable coding assistance.

* *Visual Studio Code* users should open the project directory:
+
[source,shell]
----
code .
----

. Install these extensions (kbd:[Ctrl+Shift+X] and search for `@recommended`):
+
** https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode[AsciiDoc]
** https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint[ESLint]
** https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode[Prettier]
** https://marketplace.visualstudio.com/items?itemName=arcanis.vscode-zipfs[ZipFS] (required by the Yarn SDK)

== Tasks
The `scripts` field in `package.json` defines a set of work tasks.
Corresponding configurations for IntelliJ IDEA and Visual Studio Code are located in `.idea/runConfigurations` and `.vscode/tasks.json`, respectively.

=== Create a New Validation Rule
. Invent an appropriately named rule key in dash-case (e.g. `my-rule-key`) and create a new directory with this name under `src/rules` (e.g. `src/rules/my-rule-key`).
This directory is to contain the implementation of the rule and its configuration.
. Write unit tests for the rule key configuration in `src/rules/RulesConfiguration.tests.ts`.
. Add the rule key to `ruleKeys` in `src/rules/Rule.ts` to make the unit tests pass.
. Create a factory function for the rule and activate the rule in the `rulesFrom` function in `src/validator/Validator.ts`.
.. If the rule performs any commit refinement, write unit tests for the commit refinement logic in `src/rules/Commit.tests.ts`.
.. Implement the commit refinement in the `refine` function of the rule to make the unit tests pass.
. Write unit tests for the rule logic in `src/validator/Validator.tests.ts`.
Register the rule key in the necessary dummy configurations in `src/validator/Configuration.dummies.ts`.
. Implement the rule logic in the `validate` function of the rule to make the unit tests pass.
.. If the rule is configurable, invent an appropriately named configuration key in dash-case, having the rule key as a prefix followed by two dashes (e.g. `my-rule-key--my-configuration-key`).
.. Describe the configuration in `action.yml`.
.. Write unit tests for the configuration parser in the rule directory.
.. Implement the parsing logic with a https://zod.dev/[Zod schema] in the rule directory to make the unit tests pass.
.. Add the schema to `configurationSchema` in `src/validator/Configuration.ts` and use its default value for the dummy configurations.
.. Grab the value of the corresponding input parameter in `src/github/InputParameters.ts`.
. Write unit tests for the reporter in `src/validator/Reporter.tests.ts`.
. Add instructions to the reporter in `src/validator/Reporter.ts` to make the unit tests pass.
. Describe the rule in `README.adoc` and include it in the advanced example.
. Mention the rule in `CHANGELOG.adoc` for the upcoming release.

=== Validate the Software Quality
[source,shell]
----
yarn run validate
----

It runs the following means of validation:

* *Type checking* via https://www.typescriptlang.org[TypeScript] (`validate.types`).
* *Static program analysis* (linting) via https://eslint.org[ESLint] (`validate.lint`).
** `validate.lint.fix` fixes certain issues automatically.
** `validate.lint.nocache` runs `validate.lint` without caching which is encouraged after an adjustment to the linting configuration.
** `TIMING=1 yarn run validate.lint.nocache` debugs the linting configuration to report the slowest rules.
* *Source code formatting* via https://prettier.io[Prettier] (`validate.format`).
** `validate.format.fix` reformats the files accordingly.
** `validate.format.nocache` runs `validate.format` without caching which is encouraged after an adjustment to the formatting configuration.
* *Automated unit testing* via https://vitest.dev[Vitest] (`validate.test`).
** `validate.test.coverage` creates a code coverage report in the `coverage` directory.
** `validate.test.ui` launches the https://vitest.dev/guide/ui.html[Vitest user interface] in a web browser.
** `validate.test.watch` makes the test suite run continuously.

Run `validate.fix` to automatically fix as much as possible.

=== Validate the Action Locally
. Generate a https://github.com/settings/tokens/new[personal access token on GitHub] with the `public_repo` scope.
. Store the token in a file named `.act.local` in the project root directory:
+
[source,properties,subs="+quotes,+replacements"]
----
GITHUB_TOKEN=ghp_**_<personal-access-token>_**
----
. For the sake of the test, adjust the workflow temporarily in `.github/workflows/continuous-integration.yml` to use a specific commit on GitHub from which the test run of the action is done:
+
[source,yml,subs="+quotes,+replacements"]
----
validate-commit-messages:
  [...]
  steps:
    - name: Run the validation
      uses: rainstormy/github-action-validate-commit-messages@**_<commit-sha>_**
  [...]
----

. Use https://github.com/nektos/act[Act] to run the action to verify a failing scenario and a succeeding scenario:
+
[source,shell,subs="+quotes,+replacements"]
----
act pull_request --job validate-commit-messages --secret-file .act.local --remote-name **_<origin>_** --eventpath=.github/events/pull-request-failure.json
act pull_request --job validate-commit-messages --secret-file .act.local --remote-name **_<origin>_** --eventpath=.github/events/pull-request-success.json
----

=== Build for Production
[source,shell]
----
yarn run build
----

As defined in the `action.yml` file, the generated file `dist/main.mjs` becomes the https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsmain[entrypoint of the action] which is why it is checked into the repository along with the source code.
