# Manage devtools and tasks with mise-en-place.
# https://mise.jdx.dev/configuration.html

min_version = "v2026.4.0"

[tools]
# actionlint is a linter for GitHub Actions workflows.
# https://github.com/rhysd/actionlint
actionlint = "1.7.12"

# Node.js is a JavaScript server runtime.
# https://nodejs.org
node = "24.15.0"

# pnpm is a Node.js package manager.
# https://pnpm.io
pnpm = "10.33.0"

[tasks.build]
# language=sh
run = """
  COMET_PLATFORM='cli' vite build --ssr src/main-cli.ts --outDir dist/cli/ && \
  COMET_PLATFORM='gha' vite build --ssr src/main-gha.ts --outDir dist/gha/ && \
  vite build --ssr src/legacy-v1-main.ts --outDir dist/
"""
description = "Generates production-grade build artefacts of all entrypoints with Vite."
alias = ["b"]

[tasks.check]
run = """
  oxlint --type-aware --type-check --deny-warnings && \
  oxfmt --check
"""
description = "Verifies that the source code is clean, type-safe, and well-formatted with Oxlint, TypeScript, and Oxfmt."
alias = ["c"]

[tasks.check-actions]
# language=sh
run = """
  actionlint
"""
description = "Verifies that the GitHub Actions workflows are valid with actionlint."

[tasks.check-renovate]
# language=sh
run = """
  pnpm dlx --package renovate renovate-config-validator
"""
description = "Verifies that the Renovate configuration file (`.github/renovate.json`) is valid."

[tasks.format]
# language=sh
run = """
  oxlint --fix-dangerously && \
  oxfmt
"""
description = "Applies linting suggestions with Oxlint and reformats the source code with Oxfmt."
alias = ["f"]

[tasks.install]
# language=sh
run = """
  mise install
"""
description = "Installs all third-party dependencies with mise-en-place and pnpm and (unless opted out) enables the Git hooks with Lefthook."
alias = ["i"]

[tasks.test]
# language=sh
run = """
  CI=1 COMET_PLATFORM='cli' vitest run
"""
description = "Runs the entire unit test suite once with Vitest."
alias = ["t"]

[tasks.vitest]
# language=sh
run = """
  CI=1 COMET_PLATFORM='cli' vitest watch \
    --ui \
    --api.port "$LOCALHOST_VITEST_PORT" \
    --open "$LOCALHOST_VITEST_OPENS_AUTOMATICALLY"
"""
description = "Starts the Vitest UI test explorer for continuous unit testing."
alias = ["v"]

[tasks.yolo]
# language=sh
run = """
  lefthook uninstall
"""
description = "Disables the Git hooks temporarily with Lefthook."

[hooks]
# language=sh
postinstall = """
  if [ -z "$CI" ]; then
    pnpm install --frozen-lockfile --ignore-scripts

    if [ -z "$LEFTHOOK" ] || [ "$LEFTHOOK" = '1' ] || [ "$LEFTHOOK" = 'true' ]; then
      lefthook install
    fi
  fi
"""

[env]
# Load environment variables from the following .env files in prioritised order.
# Variables declared in later files override earlier ones.
# https://mise.jdx.dev/environments/#env-file
_.file = [".env", ".env.local"]

# Make CLI programs in `node_modules` available directly in the command line.
# https://mise.jdx.dev/mise-cookbook/nodejs.html#add-node-modules-binaries-to-the-path
_.path = ["node_modules/.bin"]

# Grab the current Comet version from the `version` field in `package.json`.
COMET_VERSION = { value = "{{ exec(command=\"jq --raw-output .version package.json\") }}" }

[settings]
# Enable mise hooks.
experimental = true

# Suppress printing the `run` input command in the console when running a mise task.
quiet = true
