# Configure pnpm and manage third-party dependencies.
# https://pnpm.io/settings

# Declare third-party dependencies installed in `node_modules`.
#
# IMPORTANT: Always add a comment that describes why we need that dependency and if it has any special maintenance requirements.
# Keep in mind that adding a new dependency may increase the risk of supply chain attacks, as the attack surface grows.
catalog:
  # This library provides predefined, opinionated TypeScript configurations.
  # https://github.com/rainstormy/presets-typescript
  '@rainstormy/presets-typescript': 1.1.0

  # Type definitions for the Node.js standard library.
  # https://nodejs.org/docs/latest/api
  # https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node
  '@types/node': 24.13.2

  # The official Go-powered 'tsgo' CLI for TypeScript. It will merge with `typescript` in TypeScript 7.
  # https://github.com/microsoft/typescript-go
  '@typescript/native-preview': 7.0.0-dev.20260701.1

  # This Vitest plugin provides a test overview in the web browser.
  # https://vitest.dev/guide/ui.html
  '@vitest/ui': 4.1.10

  # Lefthook is a Git hooks manager.
  # https://lefthook.dev
  lefthook: 2.1.8

  # Oxfmt is an opinionated code formatter.
  # https://oxc.rs/docs/guide/usage/formatter.html
  oxfmt: 0.40.0

  # Oxlint is a TypeScript linter.
  # https://oxc.rs/docs/guide/usage/linter.html
  oxlint: 1.55.0

  # This Oxlint plugin provides type-aware linting rules.
  # https://github.com/oxc-project/tsgolint
  oxlint-tsgolint: 0.21.1

  # The official 'tsc' CLI for TypeScript, including the language service (LSP).
  # https://www.typescriptlang.org
  typescript: 6.0.3

  # Valibot provides type-safe data validation.
  # https://valibot.dev
  valibot: 1.4.2

  # Vite is a local development server and a bundler.
  # https://vitejs.dev
  vite: 8.1.4

  # Vitest is a unit testing framework.
  # https://vitest.dev
  vitest: 4.1.10

# Be very strict about third-party dependencies to reduce the risk of supply chain attacks.
# https://pnpm.io/blog/2025/12/05/newsroom-npm-supply-chain-security
catalogMode: strict
minimumReleaseAge: 4200 # minutes = 70 hours (3 days minus 2 hours to account for scheduling offsets in Renovate)
savePrefix: ''
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 4200 # minutes

# Disallow all script execution during package installation.
allowBuilds:
  lefthook: false

# Let some packages bypass the minimum release age requirement to allow urgent security upgrades to be installed despite being less than 3 days old.
minimumReleaseAgeExclude: []

# Consolidate transitive dependency versions with the ones specified in the catalog.
overrides: {}
