# Configure pnpm, especially to reduce the risk of supply chain attacks.
# https://pnpm.io/settings
# https://pnpm.io/blog/2025/12/05/newsroom-npm-supply-chain-security

# Disallow transitive dependencies from being installed from untrusted sources.
blockExoticSubdeps: true

# Require a minimum release age of 7 days before allowing packages to be installed.
# This reduces the risk of supply chain attacks in the npm registry.
minimumReleaseAge: 10080 # 7 * 1440 minutes

# Allow certain packages to bypass the minimum release age requirement.
# This allows urgent security upgrades to be installed despite being less than 7 days old.
# Expand the whitelist as needed. Add new packages with exact version numbers to the top.
minimumReleaseAgeExclude:
  # CVE-2026-39363 + CVE-2026-39364.
  # https://github.com/vitejs/vite/security/advisories/GHSA-p9ff-h696-f583
  # https://github.com/vitejs/vite/security/advisories/GHSA-v2wj-q39q-566r
  - 'vite@8.0.5'

  # https://github.com/oxc-project/oxc/issues/21429
  - '@oxlint-tsgolint/darwin-arm64@0.21.1'
  - '@oxlint-tsgolint/darwin-x64@0.21.1'
  - '@oxlint-tsgolint/linux-arm64@0.21.1'
  - '@oxlint-tsgolint/linux-x64@0.21.1'
  - '@oxlint-tsgolint/win32-arm64@0.21.1'
  - '@oxlint-tsgolint/win32-x64@0.21.1'
  - 'oxlint-tsgolint@0.21.1'

# Pin packages to exact versions to ensure that all developers use the same versions.
savePrefix: ''

# Disallow direct and transitive dependencies with unreviewed build scripts.
strictDepBuilds: true

# Prevent packages from being upgraded when their trust evidence or provenance is weaker than the previous version.
# This reduces the risk of installing compromised packages.
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080 # 7 * 1440 minutes
