# Configure pnpm and manage third-party dependencies.
# https://pnpm.io/settings

# Declare third-party dependencies installed in `node_modules`.
#
# IMPORTANT: Always add a comment that describes why we need that dependency and if it has any special maintenance requirements.
# Keep in mind that adding a new dependency may increase the risk of supply chain attacks, as the attack surface grows.
catalog:
  # Predefined configurations for Oxfmt, Oxlint, and TypeScript.
  # https://github.com/rainstormy/presets-web
  '@rainstormy/presets-web': 1.0.0-rc.1

  # Type definitions for the Node.js standard library.
  # https://nodejs.org/docs/latest/api
  # https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node
  '@types/node': 24.13.2

  # Lefthook is a Git hooks manager.
  # https://lefthook.dev
  lefthook: 2.1.8

  # Oxfmt is an opinionated code formatter.
  # https://oxc.rs/docs/guide/usage/formatter.html
  oxfmt: 0.60.0

  # Oxlint is a TypeScript linter.
  # https://oxc.rs/docs/guide/usage/linter.html
  oxlint: 1.75.0

  # The official 'tsc' CLI for TypeScript, including the language service (LSP) and Go-powered compiler (tsgo).
  # https://www.typescriptlang.org
  typescript: 7.0.2

  # Valibot provides type-safe data validation.
  # https://valibot.dev
  valibot: 1.4.2

  # Vite is a local development server and a bundler.
  # https://vitejs.dev
  vite: 8.1.4

  # Vite+ is a unified toolchain and task runner for Oxfmt, Oxlint, Vite, and Vitest.
  # It is also a version manager of Node.js and pnpm.
  # https://viteplus.dev
  vite-plus: 0.2.6

  # Vitest is a unit testing framework.
  # https://vitest.dev
  vitest: 4.1.10

# Be very strict about third-party dependencies to reduce the risk of supply chain attacks.
# https://pnpm.io/blog/2025/12/05/newsroom-npm-supply-chain-security
catalogMode: strict
minimumReleaseAge: 4200 # minutes = 70 hours (3 days minus 2 hours to account for scheduling offsets in Renovate)
savePrefix: ''
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 4200 # minutes

# Disallow all script execution during package installation.
allowBuilds:
  lefthook: false

# Let some packages bypass the minimum release age requirement to allow urgent security upgrades to be installed despite being less than 3 days old.
minimumReleaseAgeExclude:
  - '@rainstormy/presets-web@1.0.0-rc.1'
  - '@voidzero-dev/vite-plus-core@0.2.6'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.2.6'
  - '@voidzero-dev/vite-plus-darwin-x64@0.2.6'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.6'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.2.6'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.2.6'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.2.6'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.6'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.2.6'
  - vite-plus@0.2.6
