= Validate Commit Messages in Pull Requests
:experimental:
:source-highlighter: highlight.js
:toc: preamble

This repository implements a reusable GitHub Action that validates commit messages in pull requests on GitHub to ensure that the commit messages meet certain standards and to remind you about squash commits that must be consolidated before you merge the pull request.

It checks the commits that are about to be delivered to the target branch.
It does not check any commits outside the pull request such as existing commits that have already been merged to the target branch in a previous pull request.

== Usage
Define a GitHub Actions workflow that runs on pull requests:

[source,yaml]
----
# .github/workflows/validate-pull-requests.yml
name: Validate pull requests
on: [pull_request]
jobs:
  validate-commit-messages:
    name: Validate commit messages
    runs-on: ubuntu-latest
    steps:
      - name: Validate the commit messages
        uses: rainstormy/github-action-validate-commit-messages@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          rules: no-merge-commits, no-squash-commits
----

Here is a more elaborate example that uses all the available rules and tweaks the configuration of some of them:

[source,yaml]
----
with:
  github-token: ${{ secrets.GITHUB_TOKEN }}
  rules: acknowledged-author-email-addresses, acknowledged-author-names, acknowledged-committer-email-addresses, acknowledged-committer-names, capitalised-subject-lines, empty-line-after-subject-lines, imperative-subject-lines, issue-references-in-subject-lines, limit-length-of-body-lines, limit-length-of-subject-lines, multi-word-subject-lines, no-co-authors, no-merge-commits, no-revert-revert-commits, no-squash-commits, no-trailing-punctuation-in-subject-lines, no-unexpected-whitespace, unique-subject-lines
  acknowledged-author-email-addresses--patterns: '\d+\+.+@users\.noreply\.github\.com'
  acknowledged-author-names--patterns: '.+\s.+'
  acknowledged-committer-email-addresses--patterns: '\d+\+.+@users\.noreply\.github\.com'
  acknowledged-committer-names--patterns: '.+\s.+'
  issue-references-in-subject-lines--allowed-positions: as-suffix
  issue-references-in-subject-lines--patterns: '\(#[1-9][0-9]*\) #[1-9][0-9]*'
----

== Rules

=== `acknowledged-author-email-addresses`
The author of each commit must use an email address that matches one of the regular expressions in the `+acknowledged-author-email-addresses--patterns+` input parameter.

Standardising the author format will help you preserve the traceability of the commit history and avoid leaking personal information (e.g. a private email address) inadvertently.

==== Configuration
|===
|Input Parameter |Description |Default Value

m|+acknowledged-author-email-addresses--patterns+
|A space-separated list of regular expressions of email addresses to accept.
|`+^\b$+` _(a regular expression that never matches anything)_
|===

==== Examples (GitHub Noreply)
A regular expression of `+\d+\+.+@users\.noreply\.github\.com+` makes the rule accept personal noreply email addresses on GitHub:

|===
|✅ Accepted |⛔ Rejected

m|+19891117+littlemermaid@users.noreply.github.com+
m|+little.mermaid@theocean.com+

m|+18920129+santaclaus@users.noreply.github.com+
m|+claus@santasworkshop.com+

m|+12345678+username@users.noreply.github.com+
m|+noreply@github.com+
|===

=== `acknowledged-author-names`
The author of each commit must use a name that matches one of the regular expressions in the `+acknowledged-author-names--patterns+` input parameter.

Standardising the author format will help you preserve the traceability of the commit history and avoid leaking personal information inadvertently.

==== Configuration
|===
|Input Parameter |Description |Default Value

m|+acknowledged-author-names--patterns+
|A space-separated list of regular expressions of names to accept.
|`+^\b$+` _(a regular expression that never matches anything)_
|===

==== Examples (Multi-Word Names)
A regular expression of `+\p{Lu}.*\s.++` makes the rule accept names that have at least two words where the first one starts with an uppercase letter:

|===
|✅ Accepted |⛔ Rejected

m|The Little Mermaid
m|the little mermaid

m|Santa Claus
m|Santa.claus

m|Jeanne d'Arc
m|Jeanne
|===

=== `acknowledged-committer-email-addresses`
The committer of each commit must use an email address that matches one of the regular expressions in the `+acknowledged-committer-email-addresses--patterns+` input parameter.

By disallowing `noreply@github.com` as a committer email address, you can catch commits made through the GitHub web interface such as code review suggestions.

Standardising the committer format will help you preserve the traceability of the commit history and avoid leaking personal information (e.g. a private email address) inadvertently.

==== Configuration
|===
|Input Parameter |Description |Default Value

m|+acknowledged-committer-email-addresses--patterns+
|A space-separated list of regular expressions of email addresses to accept.
|`+^\b$+` _(a regular expression that never matches anything)_
|===

==== Examples (GitHub Noreply)
A regular expression of `+\d+\+.+@users\.noreply\.github\.com+` makes the rule accept personal noreply email addresses on GitHub:

|===
|✅ Accepted |⛔ Rejected

m|+19891117+littlemermaid@users.noreply.github.com+
m|+little.mermaid@theocean.com+

m|+18920129+santaclaus@users.noreply.github.com+
m|+claus@santasworkshop.com+

m|+12345678+username@users.noreply.github.com+
m|+noreply@github.com+
|===

=== `acknowledged-committer-names`
The committer of each commit must use a name that matches one of the regular expressions in the `+acknowledged-committer-names--patterns+` input parameter.

Standardising the committer format will help you preserve the traceability of the commit history and avoid leaking personal information inadvertently.

==== Configuration
|===
|Input Parameter |Description |Default Value

m|+acknowledged-committer-names--patterns+
|A space-separated list of regular expressions of names to accept.
|`+^\b$+` _(a regular expression that never matches anything)_
|===

==== Examples (Multi-Word Names)
A regular expression of `+\p{Lu}.*\s.++` makes the rule accept names that have at least two words where the first one starts with an uppercase letter:

|===
|✅ Accepted |⛔ Rejected

m|The Little Mermaid
m|the little mermaid

m|Santa Claus
m|Santa.claus

m|Jeanne d'Arc
m|Jeanne
|===

=== `capitalised-subject-lines`
The subject line of each commit must start with an uppercase letter.

Standardising the commit message format will help you preserve the readability of the commit history.

==== Examples
|===
|✅ Accepted |⛔ Rejected

m|Add a new feature
m|add a new feature

m|Fix a bug
m|fix a bug

m|Refactor the code
m|refactor the code
|===

=== `empty-line-after-subject-lines`
The subject line and the message body of each commit must be separated by an empty line.

Standardising the commit message format will help you preserve the readability of the commit history.

==== Examples
|===
|✅ Accepted |⛔ Rejected

m|Add a new feature

This commit adds a new feature.
m|Add a new feature +
This commit adds a new feature.

m|Fix a bug

It won't be bugging the users any more.
m|Fix a bug +
It won't be bugging the users any more.

m|Refactor the code

The main module is much more flexible now.
m|Refactor the code +
The main module is much more flexible now.
|===

=== `imperative-subject-lines`
The subject line of each commit must start with a verb in the imperative mood so that it reads like an instruction.

Standardising the commit message format will help you preserve the readability of the commit history.

==== Configuration
|===
|Input Parameter |Description |Default Value

|`+imperative-subject-lines--whitelist+`
|A comma-separated, case-insensitive list of additional words to accept.

For example, a whitelist of `chatify, deckenize` makes the rule accept subject lines that start with one of the fictive words 'chatify' or 'deckenize', in addition to subject lines that start with one of the 4,000+ verbs which are baked into the rule.
|_(empty)_
|===

==== Examples (Default Configuration)
|===
|✅ Accepted |⛔ Rejected

m|Add a new feature
m|Added a new feature

m|Format the code
m|Formatting

m|Make it work
m|It works

m|Do the validation every time
m|Always validate
|===

=== `issue-references-in-subject-lines`
The subject line of each commit must contain at least one reference to an issue tracking system that matches one of the regular expressions in the `+issue-references-in-subject-lines--patterns+` input parameter.
Exceptions to this rule include merge commits and revert commits.

Providing more context in the commit message (such as an issue reference) will help you preserve the traceability of the commit history.

==== Configuration
|===
|Input Parameter |Description |Default Value

m|+issue-references-in-subject-lines--allowed-positions+
|A comma-separated list of positions in the subject line where the issue reference is allowed to appear.

`as-prefix` allows issue references to appear at the start of the subject line.

`as-suffix` allows issue references to appear at the end of the subject line.
|`as-prefix, as-suffix`

m|+issue-references-in-subject-lines--patterns+
|A space-separated list of regular expressions of issue references to recognise.

The declaration order matters, as it resolves the issue references in the order they are listed.
Please take care not to shadow a specific regular expression with a more general one declared earlier in the list.
|`+^\b$+` _(a regular expression that never matches anything)_
|===

==== Examples (GitHub/GitLab)
When `as-suffix` is the only allowed position, a list of regular expressions of `+\(#[1-9][0-9]*\) #[1-9][0-9]*+` makes the rule recognise GitHub/GitLab-style issue references in the form of `#123` at the end of the subject line, potentially enclosed by parentheses:

|===
|✅ Accepted |⛔ Rejected

m|Introduce a cool feature #123
m|Introduce a cool feature

m|Write unit tests (#42)
m|(#42) Write unit tests

m|Fix the bug #1 #2
m|Close #1 and #2 by fixing the bug
|===

==== Examples (Jira/YouTrack)
When `as-prefix, as-suffix` are the allowed positions, a list of regular expressions of `+\(UNICORN-[1-9][0-9]*\) UNICORN-[1-9][0-9]*+` makes the rule recognise Jira/YouTrack-style issue references in the form of `UNICORN-123` at the start or the end of the subject line, potentially enclosed by parentheses:

|===
|✅ Accepted |⛔ Rejected

m|UNICORN-123 Introduce a cool feature
m|Introduce a cool feature #123

m|Write unit tests (UNICORN-42)
m|Write unit tests (UNICORN-042)

m|fixup! UNICORN-1 UNICORN-2 Fix the bug
m|Close UNICORN-1 and UNICORN-2 by fixing the bug
|===

=== `limit-length-of-body-lines`
Each line of the message body of each commit must not exceed the number of characters specified in the `+limit-length-of-body-lines--max-characters+` input parameter.
Exceptions to this rule include merge conflict lists, lines within verbatim zones enclosed by +```triple backticks```+, and lines that contain a section enclosed by +`backticks`+.

Keeping the body lines short will help you preserve the readability of the commit history in various Git clients.

==== Configuration
|===
|Input Parameter |Description |Default Value

m|+limit-length-of-body-lines--max-characters+
|The maximum number of characters allowed per line in the message body.
It must be a positive integer.
m|72
|===

==== Examples (Default Configuration)
|===
|✅ Accepted |⛔ Rejected

m|Help fix the bug

It was just a matter of time before it would cause customers to grumble.

m|Help fix the bug

It was just a matter of time before it would cause customers to complain.

m|Merge branch 'main' into feature/dance-party

Conflicts: +
{nbsp}src/some/very/nested/directory/extremely-grumpy-cat-with-surprising-features.test.ts
m|Forget to close a backtick section

This commit forgets to close the backtick section in `RapidTransportService.

m|Update dependencies

This commit updates some third-party dependencies:

+```shell+ +
yarn update --exact @elements/hydrogen@1.0.0 @elements/nitrogen@2.5.0 @elements/oxygen@2.6.0 +
+```+

m|Update dependencies

This commit updates some third-party dependencies by running the following command:

+```shell+ +
yarn update --exact @elements/hydrogen@1.0.0 @elements/nitrogen@2.5.0 @elements/oxygen@2.6.0 +
+```+
|===

=== `limit-length-of-subject-lines`
The subject line of each commit must not exceed the number of characters specified in the `+limit-length-of-subject-lines--max-characters+` input parameter.
Exceptions to this rule include merge commits, revert commits, and subject lines that contain a section enclosed by +`backticks`+.
Issue references and squash commit prefixes do not count towards the limit.

Keeping the subject line short will help you preserve the readability of the commit history in various Git clients.

==== Configuration
|===
|Input Parameter |Description |Default Value

m|+limit-length-of-subject-lines--max-characters+
|The maximum number of characters allowed in the subject line.
It must be a positive integer.
m|50
|===

==== Examples (Default Configuration)
|===
|✅ Accepted |⛔ Rejected

m|squash! Retrieve some data from the fast external services
m|Retrieve some data from the quick external services

m|Revert "Compare the list of items to the objects downloaded from the server"
m|Compare the list of items to the objects downloaded from the server

m|Let +`SoftIceMachineAdapter`+ produce the goods that we need
m|Forget to close the backtick section in `RapidTransportService
|===

=== `multi-word-subject-lines`
The subject line of each commit must contain at least two words.

Providing more context in the commit message (such as a thorough description) will help you preserve the traceability of the commit history.

==== Examples
|===
|✅ Accepted |⛔ Rejected

m|Test it
m|Test

m|Fix the bug
m|Fix

m|Prepare the implementation of the code
m|WIP
|===

=== `no-co-authors`
The message body must not contain `Co-authored-by:` trailers.

Removing the co-authors will help you preserve the authenticity of the commit, as co-authors are unable to sign commits.

By disallowing `Co-authored-by:` trailers, you can catch commits made through the GitHub web interface such as code review suggestions proposed by your peers.

==== Examples
|===
|✅ Accepted |⛔ Rejected

m|Update src/main.ts
m|Update src/main.ts

Co-authored-by: Santa Claus <+18920129+santaclaus@users.noreply.github.com+>

m|Implement the feature

Reported-By: Little Mermaid <+19891117+littlemermaid@users.noreply.github.com+>

m|Implement the feature

Co-Authored-By: Easter Bunny <+bunny@eastercompany.com+> +
Co-Authored-By: Santa Claus <+18920129+santaclaus@users.noreply.github.com+> +
Reported-By: Little Mermaid <+19891117+littlemermaid@users.noreply.github.com+>
|===

=== `no-merge-commits`
Merge commits must not be merged into the target branch of the pull request, reminding you to rebase your branch onto the target branch instead of merging the target branch into your branch.

Avoiding merge commits will help you preserve the traceability of the commit history as well as the ability to rebase interactively.

==== Examples
The rule considers a commit to be a merge commit when it has more than one parent commit:

|===
|✅ Accepted |⛔ Rejected

|`Merge branch 'main' into feature/dance-party` +
_(one parent commit)_
|`Merge branch 'main' into feature/dance-party` +
_(two parent commits)_

|`Keep the branch up-to-date` +
_(one parent commit)_
|`Keep the branch up-to-date` +
_(three parent commits)_
|===

=== `no-revert-revert-commits`
Commits that revert other revert commits must not be merged into the target branch of the pull request, reminding you to re-apply the original commits instead of reverting the revert commits.

Providing more context (such as the original commit message) and avoiding unnecessary commits will help you preserve the traceability of the commit history.

==== Examples
|===
|✅ Accepted |⛔ Rejected

m|Revert "Fix the bug"
m|Revert "Revert "Fix the bug""

m|Revert the revert commit
m|Revert "Revert "Revert "Fix the bug"""
|===

=== `no-squash-commits`
Squash commits must not be merged into the target branch of the pull request, reminding you to rebase interactively to consolidate the squash commits with the original commit.

Avoiding unnecessary commits will help you preserve the traceability of the commit history.

==== Configuration
|===
|Input Parameter |Description |Default Value

m|+no-squash-commits--disallowed-prefixes+
|A comma-separated, case-sensitive list of subject line prefixes to consider as squash commits.
m|amend!, fixup!, squash!
|===

==== Examples (Default Configuration)
|===
|✅ Accepted |⛔ Rejected

m|Add a new feature
m|amend! Add a new feature

m|Fix a bug
m|fixup! Fix a bug

m|Refactor the code
m|squash! Refactor the code
|===

=== `no-trailing-punctuation-in-subject-lines`
The subject line of each commit must not end with a punctuation character.
Exceptions to this rule include closing parentheses with matching opening parentheses, symbols associated with numbers, emoticons, emoji shortcodes, and characters specified in the `+no-trailing-punctuation-in-subject-lines--whitelist+` input parameter.

Standardising the commit message format will help you preserve the readability of the commit history.

==== Configuration
|===
|Input Parameter |Description |Default Value

m|+no-trailing-punctuation-in-subject-lines--whitelist+
|A space-separated list of punctuation characters to ignore.

For example, a whitelist of `. !` makes the rule accept subject lines with a trailing period or a trailing exclamation mark.
|_(empty)_
|===

==== Examples (Default Configuration)
|===
|✅ Accepted |⛔ Rejected

m|Add a new feature
m|Add a new feature.

m|Fix a bug
m|Fix a bug!

m|Refactor the code (the main module)
m|Refactor the code (

m|Update dependencies :-)
m|Update dependencies )

m|Write documentation :smile:
m|Write documentation:

m|Improve performance by 42%
m|Improve performance by x%
|===

=== `no-unexpected-whitespace`
The subject line of each commit must not contain any leading, trailing, or consecutive whitespace characters.
The message body must not contain any consecutive whitespace characters except for indentation.

Standardising the commit message format will help you preserve the readability of the commit history.

==== Examples
Space and newline characters are denoted by the `&middot;` and `&#9166;` characters, respectively, in the following examples:

|===
|✅ Accepted |⛔ Rejected

m|Write&middot;unit&middot;tests
m|Write&middot;unit&middot;&middot;tests

m|fixup!&middot;Fix&middot;the&middot;bug
m|&middot;Fix&middot;the&middot;bug

m|Implement&middot;the&middot;feature
m|Implement&middot;the&middot;feature&middot;

m|Write&middot;documentation&#9166; +
&#9166; +
&middot;&middot;This&middot;commit&middot;describes&middot;the&middot;usage.
m|Write&middot;documentation&#9166; +
&#9166; +
This&middot;commit&middot;describes&middot;&middot;the&middot;usage.
|===

=== `unique-subject-lines`
Commits that repeat the subject line of a previous commit in the pull request are probably meant to be squash commits that should be consolidated with the original commit.
Exceptions to this rule include merge commits, revert commits, and proper squash commits (as configured by `+no-squash-commits--disallowed-prefixes+`).

Avoiding unnecessary commits will help you preserve the traceability of the commit history.

==== Examples
|===
|✅ Accepted |⛔ Rejected

a|
* `Write unit tests`
* `Refactor the code`
a|
* `Refactor the code`
* `Refactor the code`

a|
* `Refactor the code`
* `squash! Refactor the code`
* `squash! Refactor the code`
a|
* `Write unit tests`
* `Implement the feature`
* `Write unit tests`
|===

== Contributing
Please take a look at link:CONTRIBUTING.adoc[CONTRIBUTING.adoc] for detailed instructions on how to contribute to this project 😀
