name: Install Node.js, npm, and Yarn
description: Runs `actions/setup-node` and restores dependencies from the Yarn zero-install cache.
author: Steffen Diswal

runs:
  using: composite
  steps:
    - name: Enable Yarn with Corepack # See https://github.com/actions/setup-node/issues/899#issuecomment-1823139737 and https://github.com/actions/setup-node/issues/531.
      run: |
        corepack enable yarn
      shell: bash
    - name: Install Node.js and npm
      uses: actions/setup-node@v4 # https://github.com/actions/setup-node
      with:
        node-version: 20
    - name: Restore unplugged dependencies from the workflow cache
      id: cache-yarn-unplugged
      uses: actions/cache@v3 # https://github.com/actions/cache
      with:
        path: .yarn/unplugged/
        key: cache-yarn-unplugged-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          cache-yarn-unplugged-${{ runner.os }}-
    - name: Make dependencies executable from package scripts
      if: steps.cache-yarn-unplugged.outputs.cache-hit != 'true'
      run: yarn install --immutable
      shell: bash
