import { describe, expect, it } from "vitest"
import { mapCrudeCommitToCommit } from "#commits/Commit.ts"
import { fakeCrudeCommit } from "#commits/CrudeCommit.fixtures.ts"
import {
	type Tokens,
	code,
	issuelink,
	punctuation,
	revert,
	semver,
	space,
	squash,
	trailerkey,
	whitespace,
	word,
} from "#commits/tokens/Token.ts"
import { fakeTokenConfiguration } from "#configurations/Configuration.fixtures.ts"

const configuration = fakeTokenConfiguration()

describe.each`
	subjectLine                                         | body                                                                                                                                                                                                                                        | expectedSubjectLine                                                                                                                                                                                                                                                            | expectedBodyLines
	${"Update src/main.ts"}                             | ${"\nCo-Authored-By: Everloving Easter Bunny <everloving.easter.bunny@example.com>"}                                                                                                                                                        | ${[word("Update"), space(6), word("src", 7), punctuation("/", 10), word("main", 11), punctuation(".", 15), word("ts", 16)]}                                                                                                                                                    | ${[[], [trailerkey("Co-Authored-By"), punctuation(":", 14), space(15), word("Everloving", 16), space(26), word("Easter", 27), space(33), word("Bunny", 34), space(39), punctuation("<", 40), word("everloving", 41), punctuation(".", 51), word("easter", 52), punctuation(".", 58), word("bunny", 59), punctuation("@", 64), word("example", 65), punctuation(".", 72), word("com", 73), punctuation(">", 76)]]}
	${"Teach the changelog to whisper"}                 | ${"\nThe noisy bits moved to the release notes.\n\nFooter: charming"}                                                                                                                                                                       | ${[word("Teach"), space(5), word("the", 6), space(9), word("changelog", 10), space(19), word("to", 20), space(22), word("whisper", 23)]}                                                                                                                                       | ${[[], [word("The"), space(3), word("noisy", 4), space(9), word("bits", 10), space(14), word("moved", 15), space(20), word("to", 21), space(23), word("the", 24), space(27), word("release", 28), space(35), word("notes", 36), punctuation(".", 41)], [], [trailerkey("Footer"), punctuation(":", 6), space(7), word("charming", 8)]]}
	${"do some pair programming"}                       | ${"\nthis commit is a collab\nco-authored-by: santa claus <santa.claus@example.com>\nco-authored-by  : gingerbread man <gingerbread.man@example.com>\nreported-by: little mermaid <little.mermaid@example.com>"}                            | ${[word("do"), space(2), word("some", 3), space(7), word("pair", 8), space(12), word("programming", 13)]}                                                                                                                                                                      | ${[[], [word("this"), space(4), word("commit", 5), space(11), word("is", 12), space(14), word("a", 15), space(16), word("collab", 17)], [trailerkey("co-authored-by"), punctuation(":", 14), space(15), word("santa", 16), space(21), word("claus", 22), space(27), punctuation("<", 28), word("santa", 29), punctuation(".", 34), word("claus", 35), punctuation("@", 40), word("example", 41), punctuation(".", 48), word("com", 49), punctuation(">", 52)], [trailerkey("co-authored-by"), whitespace("  ", 14), punctuation(":", 16), space(17), word("gingerbread", 18), space(29), word("man", 30), space(33), punctuation("<", 34), word("gingerbread", 35), punctuation(".", 46), word("man", 47), punctuation("@", 50), word("example", 51), punctuation(".", 58), word("com", 59), punctuation(">", 62)], [trailerkey("reported-by"), punctuation(":", 11), space(12), word("little", 13), space(19), word("mermaid", 20), space(27), punctuation("<", 28), word("little", 29), punctuation(".", 35), word("mermaid", 36), punctuation("@", 43), word("example", 44), punctuation(".", 51), word("com", 52), punctuation(">", 55)]]}
	${"Calibrate `HotChocolateMachine`"}                | ${"The pressure now stays pleasantly dramatic.\n Signed-off-by:Michelangelo di Lodovico Buonarroti Simoni <28317649+cowabunga@users.noreply.github.com>"}                                                                                   | ${[word("Calibrate"), space(9), code("`HotChocolateMachine`", 10)]}                                                                                                                                                                                                            | ${[[word("The"), space(3), word("pressure", 4), space(12), word("now", 13), space(16), word("stays", 17), space(22), word("pleasantly", 23), space(33), word("dramatic", 34), punctuation(".", 42)], [space(), trailerkey("Signed-off-by", 1), punctuation(":", 14), word("Michelangelo", 15), space(27), word("di", 28), space(30), word("Lodovico", 31), space(39), word("Buonarroti", 40), space(50), word("Simoni", 51), space(57), punctuation("<", 58), word("28317649", 59), punctuation("+", 67), word("cowabunga", 68), punctuation("@", 77), word("users", 78), punctuation(".", 83), word("noreply", 84), punctuation(".", 91), word("github", 92), punctuation(".", 98), word("com", 99), punctuation(">", 102)]]}
	${"Upgrade the badge printer"}                      | ${"\nThe queue no longer panics.\nSchemamaxxed the validation and protected the valuable payload.\n\nRefs :: #123\nCo-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>\n\nBREAKING CHANGE: Old badge templates are gone."} | ${[word("Upgrade"), space(7), word("the", 8), space(11), word("badge", 12), space(17), word("printer", 18)]}                                                                                                                                                                   | ${[[], [word("The"), space(3), word("queue", 4), space(9), word("no", 10), space(12), word("longer", 13), space(19), word("panics", 20), punctuation(".", 26)], [word("Schemamaxxed"), space(12), word("the", 13), space(16), word("validation", 17), space(27), word("and", 28), space(31), word("protected", 32), space(41), word("the", 42), space(45), word("valuable", 46), space(54), word("payload", 55), punctuation(".", 62)], [], [trailerkey("Refs"), space(4), punctuation(":", 5), punctuation(":", 6), space(7), punctuation("#", 8), word("123", 9)], [trailerkey("Co-authored-by"), punctuation(":", 14), space(15), word("Copilot", 16), space(23), punctuation("<", 24), word("223556219", 25), punctuation("+", 34), word("Copilot", 35), punctuation("@", 42), word("users", 43), punctuation(".", 48), word("noreply", 49), punctuation(".", 56), word("github", 57), punctuation(".", 63), word("com", 64), punctuation(">", 67)], [], [trailerkey("BREAKING CHANGE"), punctuation(":", 15), space(16), word("Old", 17), space(20), word("badge", 21), space(26), word("templates", 27), space(36), word("are", 37), space(40), word("gone", 41), punctuation(".", 45)]]}
	${"Credit the careful reviewers"}                   | ${"\n\n  Reviewed-by:  April O'Neil <april.oneil@fastforward.com>\n\nSigned-off-by: baxter.stockman <baxter.stockman@fastforward.com>\n"}                                                                                                   | ${[word("Credit"), space(6), word("the", 7), space(10), word("careful", 11), space(18), word("reviewers", 19)]}                                                                                                                                                                | ${[[], [], [whitespace("  "), trailerkey("Reviewed-by", 2), punctuation(":", 13), whitespace("  ", 14), word("April", 16), space(21), word("O'Neil", 22), space(28), punctuation("<", 29), word("april", 30), punctuation(".", 35), word("oneil", 36), punctuation("@", 41), word("fastforward", 42), punctuation(".", 53), word("com", 54), punctuation(">", 57)], [], [trailerkey("Signed-off-by"), punctuation(":", 13), space(14), word("baxter", 15), punctuation(".", 21), word("stockman", 22), space(30), punctuation("<", 31), word("baxter", 32), punctuation(".", 38), word("stockman", 39), punctuation("@", 47), word("fastforward", 48), punctuation(".", 59), word("com", 60), punctuation(">", 63)], []]}
	${"feat: document the careful shortcut"}            | ${"The body explains the shortcut.\nSigned-off-by: Master Splinter <sensei@ninja-academy.com>"}                                                                                                                                             | ${[word("feat"), punctuation(":", 4), space(5), word("document", 6), space(14), word("the", 15), space(18), word("careful", 19), space(26), word("shortcut", 27)]}                                                                                                             | ${[[word("The"), space(3), word("body", 4), space(8), word("explains", 9), space(17), word("the", 18), space(21), word("shortcut", 22), punctuation(".", 30)], [trailerkey("Signed-off-by"), punctuation(":", 13), space(14), word("Master", 15), space(21), word("Splinter", 22), space(30), punctuation("<", 31), word("sensei", 32), punctuation("@", 38), word("ninja-academy", 39), punctuation(".", 52), word("com", 53), punctuation(">", 56)]]}
	${"add some goongala to the battle shell"}          | ${"Refs: #1337\nWith extra slices of pizza!!\n\nReviewed-by: April O'Neil <april.oneil@fastforward.com>\nSigned-off-by: Casey Jones <casey.jones@fastforward.com>"}                                                                         | ${[word("add"), space(3), word("some", 4), space(8), word("goongala", 9), space(17), word("to", 18), space(20), word("the", 21), space(24), word("battle", 25), space(31), word("shell", 32)]}                                                                                 | ${[[word("Refs"), punctuation(":", 4), space(5), issuelink("#1337", 6)], [word("With"), space(4), word("extra", 5), space(10), word("slices", 11), space(17), word("of", 18), space(20), word("pizza", 21), punctuation("!", 26), punctuation("!", 27)], [], [trailerkey("Reviewed-by"), punctuation(":", 11), space(12), word("April", 13), space(18), word("O'Neil", 19), space(25), punctuation("<", 26), word("april", 27), punctuation(".", 32), word("oneil", 33), punctuation("@", 38), word("fastforward", 39), punctuation(".", 50), word("com", 51), punctuation(">", 54)], [trailerkey("Signed-off-by"), punctuation(":", 13), space(14), word("Casey", 15), space(20), word("Jones", 21), space(26), punctuation("<", 27), word("casey", 28), punctuation(".", 33), word("jones", 34), punctuation("@", 39), word("fastforward", 40), punctuation(".", 51), word("com", 52), punctuation(">", 55)]]}
	${"Record the quiet acknowledgements"}              | ${"\nReviewed-by: \nBREAKING CHANGE:"}                                                                                                                                                                                                      | ${[word("Record"), space(6), word("the", 7), space(10), word("quiet", 11), space(16), word("acknowledgements", 17)]}                                                                                                                                                           | ${[[], [trailerkey("Reviewed-by"), punctuation(":", 11), space(12)], [trailerkey("BREAKING CHANGE"), punctuation(":", 15)]]}
	${"fixup! calibrate tiny robot (#88)"}              | ${"\n  reviewed-by:   the night baker   "}                                                                                                                                                                                                  | ${[squash("fixup!"), space(6), word("calibrate", 7), space(16), word("tiny", 17), space(21), word("robot", 22), space(27), issuelink("(#88)", 28)]}                                                                                                                            | ${[[], [whitespace("  "), trailerkey("reviewed-by", 2), punctuation(":", 13), whitespace("   ", 14), word("the", 17), space(20), word("night", 21), space(26), word("baker", 27), whitespace("   ", 32)]]}
	${"squash! Teach CI to whisper GL-42"}              | ${"ACKED-BY:\tCAPTAIN STATIC\t"}                                                                                                                                                                                                            | ${[squash("squash!"), space(7), word("Teach", 8), space(13), word("CI", 14), space(16), word("to", 17), space(19), word("whisper", 20), space(27), issuelink("GL-42", 28)]}                                                                                                    | ${[[trailerkey("ACKED-BY"), punctuation(":", 8), whitespace("\t", 9), word("CAPTAIN", 10), space(17), word("STATIC", 18), whitespace("\t", 24)]]}
	${'Revert "Footer: make old parser nervous (#19)"'} | ${"\nbreaking change:   switch to quieter alarms   "}                                                                                                                                                                                       | ${[revert("Revert"), space(6), punctuation('"', 7), word("Footer", 8), punctuation(":", 14), space(15), word("make", 16), space(20), word("old", 21), space(24), word("parser", 25), space(31), word("nervous", 32), space(39), issuelink("(#19)", 40), punctuation('"', 45)]} | ${[[], [trailerkey("breaking change"), punctuation(":", 15), whitespace("   ", 16), word("switch", 19), space(25), word("to", 26), space(28), word("quieter", 29), space(36), word("alarms", 37), whitespace("   ", 43)]]}
	${"deps: lower the tiny boom"}                      | ${"WISHLIST :   cake first, tests second   "}                                                                                                                                                                                               | ${[word("deps"), punctuation(":", 4), space(5), word("lower", 6), space(11), word("the", 12), space(15), word("tiny", 16), space(20), word("boom", 21)]}                                                                                                                       | ${[[trailerkey("WISHLIST"), space(8), punctuation(":", 9), whitespace("   ", 10), word("cake", 13), space(17), word("first", 18), punctuation(",", 23), space(24), word("tests", 25), space(30), word("second", 31), whitespace("   ", 37)]]}
	${"Add GPS notes"}                                  | ${"Refs: the map says key: value: keep walking"}                                                                                                                                                                                            | ${[word("Add"), space(3), word("GPS", 4), space(7), word("notes", 8)]}                                                                                                                                                                                                         | ${[[trailerkey("Refs"), punctuation(":", 4), space(5), word("the", 6), space(9), word("map", 10), space(13), word("says", 14), space(18), word("key", 19), punctuation(":", 22), space(23), word("value", 24), punctuation(":", 29), space(30), word("keep", 31), space(35), word("walking", 36)]]}
	${"Plan the loud migration"}                        | ${"\n\n\nBREAKING CHANGE: config now accepts host:port:mode"}                                                                                                                                                                               | ${[word("Plan"), space(4), word("the", 5), space(8), word("loud", 9), space(13), word("migration", 14)]}                                                                                                                                                                       | ${[[], [], [], [trailerkey("BREAKING CHANGE"), punctuation(":", 15), space(16), word("config", 17), space(23), word("now", 24), space(27), word("accepts", 28), space(35), word("host", 36), punctuation(":", 40), word("port", 41), punctuation(":", 45), word("mode", 46)]]}
	${"document the field notes"}                       | ${"co-authored-by: Donatello <42069849+gogogadget@users.noreply.github.com>: with field notes"}                                                                                                                                             | ${[word("document"), space(8), word("the", 9), space(12), word("field", 13), space(18), word("notes", 19)]}                                                                                                                                                                    | ${[[trailerkey("co-authored-by"), punctuation(":", 14), space(15), word("Donatello", 16), space(25), punctuation("<", 26), word("42069849", 27), punctuation("+", 35), word("gogogadget", 36), punctuation("@", 46), word("users", 47), punctuation(".", 52), word("noreply", 53), punctuation(".", 60), word("github", 61), punctuation(".", 67), word("com", 68), punctuation(">", 71), punctuation(":", 72), space(73), word("with", 74), space(78), word("field", 79), space(84), word("notes", 85)]]}
`(
	"when the commit message of $body contains trailers",
	(props: {
		subjectLine: string
		body: string
		expectedSubjectLine: Tokens
		expectedBodyLines: Array<Tokens>
	}) => {
		const crudeCommit = fakeCrudeCommit({ message: `${props.subjectLine}\n${props.body}` })

		it("leaves the subject line unchanged", () => {
			const commit = mapCrudeCommitToCommit(crudeCommit, configuration)
			expect(commit.subjectLine).toEqual(props.expectedSubjectLine)
		})

		it("extracts trailer tokens in the message body", () => {
			const commit = mapCrudeCommitToCommit(crudeCommit, configuration)
			expect(commit.bodyLines).toEqual(props.expectedBodyLines)
		})
	},
)

describe.each`
	subjectLine                               | body                                                                                                                                                                                                                          | expectedSubjectLine                                                                                                                                                                     | expectedBodyLines
	${"Explain the suspicious label"}         | ${"Refs: This looked official for a moment.\nThen the paragraph kept going."}                                                                                                                                                 | ${[word("Explain"), space(7), word("the", 8), space(11), word("suspicious", 12), space(22), word("label", 23)]}                                                                         | ${[[word("Refs"), punctuation(":", 4), space(5), word("This", 6), space(10), word("looked", 11), space(17), word("official", 18), space(26), word("for", 27), space(30), word("a", 31), space(32), word("moment", 33), punctuation(".", 39)], [word("Then"), space(4), word("the", 5), space(8), word("paragraph", 9), space(18), word("kept", 19), space(23), word("going", 24), punctuation(".", 29)]]}
	${"Do some pair programming"}             | ${"\nThis commit is a collab.\n\nCo-authored-by: Gon Freecss <rock.paper.scissors@hunters.com>\nCo-authored-by: Killua Zoldyck <killua@godspeed.net>\n Reported-by: Hisoka <no4@phantom.com>\n\nAll participants had fun.\n"} | ${[word("Do"), space(2), word("some", 3), space(7), word("pair", 8), space(12), word("programming", 13)]}                                                                               | ${[[], [word("This"), space(4), word("commit", 5), space(11), word("is", 12), space(14), word("a", 15), space(16), word("collab", 17), punctuation(".", 23)], [], [word("Co-authored-by"), punctuation(":", 14), space(15), word("Gon", 16), space(19), word("Freecss", 20), space(27), punctuation("<", 28), word("rock", 29), punctuation(".", 33), word("paper", 34), punctuation(".", 39), word("scissors", 40), punctuation("@", 48), word("hunters", 49), punctuation(".", 56), word("com", 57), punctuation(">", 60)], [word("Co-authored-by"), punctuation(":", 14), space(15), word("Killua", 16), space(22), word("Zoldyck", 23), space(30), punctuation("<", 31), word("killua", 32), punctuation("@", 38), word("godspeed", 39), punctuation(".", 47), word("net", 48), punctuation(">", 51)], [space(), word("Reported-by", 1), punctuation(":", 12), space(13), word("Hisoka", 14), space(20), punctuation("<", 21), word("no4", 22), punctuation("@", 25), word("phantom", 26), punctuation(".", 33), word("com", 34), punctuation(">", 37)], [], [word("All"), space(3), word("participants", 4), space(16), word("had", 17), space(20), word("fun", 21), punctuation(".", 24)], []]}
	${"fixup! keep the lowercase memo"}       | ${"Footer: looks real\nthen it keeps talking"}                                                                                                                                                                                | ${[squash("fixup!"), space(6), word("keep", 7), space(11), word("the", 12), space(15), word("lowercase", 16), space(25), word("memo", 26)]}                                             | ${[[word("Footer"), punctuation(":", 6), space(7), word("looks", 8), space(13), word("real", 14)], [word("then"), space(4), word("it", 5), space(7), word("keeps", 8), space(13), word("talking", 14)]]}
	${"SQUASH! no token here maybe"}          | ${"ACKED-BY: The Captain\nordinary words after the captain"}                                                                                                                                                                  | ${[squash("SQUASH!"), space(7), word("no", 8), space(10), word("token", 11), space(16), word("here", 17), space(21), word("maybe", 22)]}                                                | ${[[word("ACKED-BY"), punctuation(":", 8), space(9), word("The", 10), space(13), word("Captain", 14)], [word("ordinary"), space(8), word("words", 9), space(14), word("after", 15), space(20), word("the", 21), space(24), word("captain", 25)]]}
	${'Revert "reviewed-by: subject mirage"'} | ${"breaking change: seems important\nbut this paragraph is still alive"}                                                                                                                                                      | ${[revert("Revert"), space(6), punctuation('"', 7), word("reviewed-by", 8), punctuation(":", 19), space(20), word("subject", 21), space(28), word("mirage", 29), punctuation('"', 35)]} | ${[[word("breaking"), space(8), word("change", 9), punctuation(":", 15), space(16), word("seems", 17), space(22), word("important", 23)], [word("but"), space(3), word("this", 4), space(8), word("paragraph", 9), space(18), word("is", 19), space(21), word("still", 22), space(27), word("alive", 28)]]}
`(
	"when the commit message of $body contains trailer-like lines followed by regular lines of text",
	(props: {
		subjectLine: string
		body: string
		expectedSubjectLine: Tokens
		expectedBodyLines: Array<Tokens>
	}) => {
		const crudeCommit = fakeCrudeCommit({ message: `${props.subjectLine}\n${props.body}` })

		it("leaves the subject line unchanged", () => {
			const commit = mapCrudeCommitToCommit(crudeCommit, configuration)
			expect(commit.subjectLine).toEqual(props.expectedSubjectLine)
		})

		it("leaves the body lines unchanged", () => {
			const commit = mapCrudeCommitToCommit(crudeCommit, configuration)
			expect(commit.bodyLines).toEqual(props.expectedBodyLines)
		})
	},
)

describe.each`
	subjectLine                                                         | body                                                                                                                                                                                                                                                                                                                                                      | expectedSubjectLine                                                                                                                                                                                                                                                                     | expectedBodyLines
	${"bugfix"}                                                         | ${"attempt 2"}                                                                                                                                                                                                                                                                                                                                            | ${[word("bugfix")]}                                                                                                                                                                                                                                                                     | ${[[word("attempt"), space(7), word("2", 8)]]}
	${"Refactor the taxi module"}                                       | ${"The roof sign now flashes politely."}                                                                                                                                                                                                                                                                                                                  | ${[word("Refactor"), space(8), word("the", 9), space(12), word("taxi", 13), space(17), word("module", 18)]}                                                                                                                                                                             | ${[[word("The"), space(3), word("roof", 4), space(8), word("sign", 9), space(13), word("now", 14), space(17), word("flashes", 18), space(25), word("politely", 26), punctuation(".", 34)]]}
	${"Resolve the conflicts"}                                          | ${"\nConflicts:\n\n src/grumpy-cat.ts\n src/summer-vacation-plans.ts"}                                                                                                                                                                                                                                                                                    | ${[word("Resolve"), space(7), word("the", 8), space(11), word("conflicts", 12)]}                                                                                                                                                                                                        | ${[[], [word("Conflicts"), punctuation(":", 9)], [], [space(), word("src", 1), punctuation("/", 4), word("grumpy-cat", 5), punctuation(".", 15), word("ts", 16)], [space(), word("src", 1), punctuation("/", 4), word("summer-vacation-plans", 5), punctuation(".", 26), word("ts", 27)]]}
	${"fixup! Upgrade @typescript-eslint/parser from 5.52.0 to 5.59.1"} | ${"\n\n\n\nBumps [@typescript-eslint/parser](https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/parser) from 5.52.0 to 5.59.1.\n- [Release notes](https://github.com/typescript-eslint/typescript-eslint/releases)\n- [Changelog](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/parser/CHANGELOG.md)"} | ${[squash("fixup!"), space(6), word("Upgrade", 7), space(14), punctuation("@", 15), word("typescript-eslint", 16), punctuation("/", 33), word("parser", 34), space(40), word("from", 41), space(45), semver("5.52.0", 46), space(52), word("to", 53), space(55), semver("5.59.1", 56)]} | ${[[], [], [], [], [word("Bumps"), space(5), punctuation("[", 6), punctuation("@", 7), word("typescript-eslint", 8), punctuation("/", 25), word("parser", 26), punctuation("]", 32), punctuation("(", 33), word("https", 34), punctuation(":", 39), punctuation("/", 40), punctuation("/", 41), word("github", 42), punctuation(".", 48), word("com", 49), punctuation("/", 52), word("typescript-eslint", 53), punctuation("/", 70), word("typescript-eslint", 71), punctuation("/", 88), word("tree", 89), punctuation("/", 93), word("HEAD", 94), punctuation("/", 98), word("packages", 99), punctuation("/", 107), word("parser", 108), punctuation(")", 114), space(115), word("from", 116), space(120), word("5", 121), punctuation(".", 122), word("52", 123), punctuation(".", 125), word("0", 126), space(127), word("to", 128), space(130), word("5", 131), punctuation(".", 132), word("59", 133), punctuation(".", 135), word("1", 136), punctuation(".", 137)], [punctuation("-"), space(1), punctuation("[", 2), word("Release", 3), space(10), word("notes", 11), punctuation("]", 16), punctuation("(", 17), word("https", 18), punctuation(":", 23), punctuation("/", 24), punctuation("/", 25), word("github", 26), punctuation(".", 32), word("com", 33), punctuation("/", 36), word("typescript-eslint", 37), punctuation("/", 54), word("typescript-eslint", 55), punctuation("/", 72), word("releases", 73), punctuation(")", 81)], [punctuation("-"), space(1), punctuation("[", 2), word("Changelog", 3), punctuation("]", 12), punctuation("(", 13), word("https", 14), punctuation(":", 19), punctuation("/", 20), punctuation("/", 21), word("github", 22), punctuation(".", 28), word("com", 29), punctuation("/", 32), word("typescript-eslint", 33), punctuation("/", 50), word("typescript-eslint", 51), punctuation("/", 68), word("blob", 69), punctuation("/", 73), word("main", 74), punctuation("/", 78), word("packages", 79), punctuation("/", 87), word("parser", 88), punctuation("/", 94), word("CHANGELOG", 95), punctuation(".", 104), word("md", 105), punctuation(")", 107)]]}
	${"lowercase chores only"}                                          | ${"This body mentions refs: #44 inline."}                                                                                                                                                                                                                                                                                                                 | ${[word("lowercase"), space(9), word("chores", 10), space(16), word("only", 17)]}                                                                                                                                                                                                       | ${[[word("This"), space(4), word("body", 5), space(9), word("mentions", 10), space(18), word("refs", 19), punctuation(":", 23), space(24), issuelink("#44", 25), space(28), word("inline", 29), punctuation(".", 35)]]}
	${"squash! refs: subject mirage"}                                   | ${"\nBREAKING CHANGE - not a colon trailer\nCo-authored-by = missing colon"}                                                                                                                                                                                                                                                                              | ${[squash("squash!"), space(7), word("refs", 8), punctuation(":", 12), space(13), word("subject", 14), space(21), word("mirage", 22)]}                                                                                                                                                  | ${[[], [word("BREAKING"), space(8), word("CHANGE", 9), space(15), punctuation("-", 16), space(17), word("not", 18), space(21), word("a", 22), space(23), word("colon", 24), space(29), word("trailer", 30)], [word("Co-authored-by"), space(14), punctuation("=", 15), space(16), word("missing", 17), space(24), word("colon", 25)]]}
	${'Revert "Signed-off-by: subject mirage"'}                         | ${"Signed-off-by:\nNo final trailer follows this sentence."}                                                                                                                                                                                                                                                                                              | ${[revert("Revert"), space(6), punctuation('"', 7), word("Signed-off-by", 8), punctuation(":", 21), space(22), word("subject", 23), space(30), word("mirage", 31), punctuation('"', 37)]}                                                                                               | ${[[word("Signed-off-by"), punctuation(":", 13)], [word("No"), space(2), word("final", 3), space(8), word("trailer", 9), space(16), word("follows", 17), space(24), word("this", 25), space(29), word("sentence", 30), punctuation(".", 38)]]}
	${"Add GPS notes"}                                                  | ${"trailer-like: starts the body\nregular line closes the paragraph"}                                                                                                                                                                                                                                                                                     | ${[word("Add"), space(3), word("GPS", 4), space(7), word("notes", 8)]}                                                                                                                                                                                                                  | ${[[word("trailer-like"), punctuation(":", 12), space(13), word("starts", 14), space(20), word("the", 21), space(24), word("body", 25)], [word("regular"), space(7), word("line", 8), space(12), word("closes", 13), space(19), word("the", 20), space(23), word("paragraph", 24)]]}
`(
	"when the commit message of $body does not contain any trailers",
	(props: {
		subjectLine: string
		body: string
		expectedSubjectLine: Tokens
		expectedBodyLines: Array<Tokens>
	}) => {
		const crudeCommit = fakeCrudeCommit({ message: `${props.subjectLine}\n${props.body}` })

		it("leaves the subject line unchanged", () => {
			const commit = mapCrudeCommitToCommit(crudeCommit, configuration)
			expect(commit.subjectLine).toEqual(props.expectedSubjectLine)
		})

		it("leaves the body lines unchanged", () => {
			const commit = mapCrudeCommitToCommit(crudeCommit, configuration)
			expect(commit.bodyLines).toEqual(props.expectedBodyLines)
		})
	},
)

describe.each`
	subjectLine                                                    | expectedSubjectLine
	${"Refs: This looked official for a moment."}                  | ${[word("Refs"), punctuation(":", 4), space(5), word("This", 6), space(10), word("looked", 11), space(17), word("official", 18), space(26), word("for", 27), space(30), word("a", 31), space(32), word("moment", 33), punctuation(".", 39)]}
	${"Signed-off-by: April O'Neil <april.oneil@fastforward.com>"} | ${[word("Signed-off-by"), punctuation(":", 13), space(14), word("April", 15), space(20), word("O'Neil", 21), space(27), punctuation("<", 28), word("april", 29), punctuation(".", 34), word("oneil", 35), punctuation("@", 40), word("fastforward", 41), punctuation(".", 52), word("com", 53), punctuation(">", 56)]}
	${"BREAKING CHANGE: The old badge printer retired."}           | ${[word("BREAKING"), space(8), word("CHANGE", 9), punctuation(":", 15), space(16), word("The", 17), space(20), word("old", 21), space(24), word("badge", 25), space(30), word("printer", 31), space(38), word("retired", 39), punctuation(".", 46)]}
	${"Refs: looks official in the subject (#12)"}                 | ${[word("Refs"), punctuation(":", 4), space(5), word("looks", 6), space(11), word("official", 12), space(20), word("in", 21), space(23), word("the", 24), space(27), word("subject", 28), space(35), issuelink("(#12)", 36)]}
	${"signed-off-by: lowercase subject only"}                     | ${[word("signed-off-by"), punctuation(":", 13), space(14), word("lowercase", 15), space(24), word("subject", 25), space(32), word("only", 33)]}
	${"ACKED-BY: SUBJECT ONLY"}                                    | ${[word("ACKED-BY"), punctuation(":", 8), space(9), word("SUBJECT", 10), space(17), word("ONLY", 18)]}
`(
	"when the subject line looks like a trailer",
	(props: { subjectLine: string; expectedSubjectLine: Tokens }) => {
		const crudeCommit = fakeCrudeCommit({ message: props.subjectLine })

		it("leaves the subject line unchanged", () => {
			const commit = mapCrudeCommitToCommit(crudeCommit, configuration)
			expect(commit.subjectLine).toEqual(props.expectedSubjectLine)
		})

		it("has no body lines", () => {
			const commit = mapCrudeCommitToCommit(crudeCommit, configuration)
			expect(commit.bodyLines).toEqual([])
		})
	},
)
