name: pnpm
description: Installs pnpm and third-party dependencies.

# All third-party actions are pinned to a specific commit SHA for security reasons.
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      #
    - name: Install Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        cache: pnpm
        node-version-file: ./.nvmrc
        registry-url: https://registry.npmjs.org
      #
    - name: Install third-party dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
