# This workflow implements the second stage of the release pipeline.
# It creates version tags in Git on the merge commit from the release branch.
#
# It is triggered by merging the pull request from `.github/workflows/release.yml`.

name: Publish / Tags

on:
  pull_request:
    branches:
      - main
    paths:
      # Limit the workflow to pull requests that modify `package.json` to reduce clutter in the 'Workflow runs' overview in GitHub Actions.
      - package.json
    types:
      - closed

# Cancel all previous runs of this workflow that are still in progress on the same branch.
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: publish-tags-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# All third-party actions are pinned to a specific commit SHA for security reasons.
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
jobs:
  tags:
    name: Tags
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 1
    permissions: { }
    steps:
      - name: Check out the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # Use a separate access token to allow the push tag event in this workflow to trigger `.github/workflows/publish-github.yml`.
          # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
          token: ${{ secrets.BOT_NIMBUS_GH_AUTH_TOKEN }}
        #
      - name: Use Nimbus (Bot) in Git
        uses: rainstormy/rainstorm-release/bot-nimbus@5aa67a14e95403e7db0a7a43f8e18c1cdd51ba5f # v1.0.0
        with:
          bot-nimbus-ssh-public-key: ${{ secrets.BOT_NIMBUS_SSH_PUBLIC_KEY }}
          __bot-nimbus-ssh-private-key__: ${{ secrets.BOT_NIMBUS_SSH___THE___PRIVATE___KEY }}
          ssh-key-fingerprints-github: ${{ secrets.SSH_KEY_FINGERPRINTS_GITHUB }}
        #
      - name: Create a full semantic version tag in Git
        uses: rainstormy/release/tag@eb87dc4ba5e9e89451adce4a3c62538e5ecef809 # v1.1.1
        with:
          version: ${{ github.head_ref }}
        #
      - name: Create a major-only version tag in Git
        uses: rainstormy/release/major-tag@eb87dc4ba5e9e89451adce4a3c62538e5ecef809 # v1.1.1
        with:
          version: ${{ github.head_ref }}
