# This workflow creates a draft GitHub release from a Git tag.
#
# It is triggered automatically by pushing a Git tag with a `v` prefix, as done by the `release-tag.yml` workflow.
#
# It can be triggered manually via the GitHub CLI:
#   gh workflow run release-github.yml --ref <tag-name>
#   gh run watch
#
# It can be triggered manually via the GitHub web interface:
#   https://github.com/rainstormy/github-action-validate-commit-messages/actions/workflows/release-github.yml

name: Release / GitHub

on:
  push:
    tags:
      - v*
  workflow_dispatch:

# Cancel all previous runs of this workflow that are still in progress on the same branch.
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: release-github-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# All third-party actions are pinned to a specific commit SHA for security reasons.
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
jobs:
  quality-assurance:
    name: Quality assurance
    permissions:
      contents: read # Allow the job to call the reusable `ci.yml` workflow.
      pull-requests: read # `ci.yml` requires `pull-requests` read permissions.
    uses: ./.github/workflows/ci.yml

  github-release:
    name: GitHub release
    needs: quality-assurance
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    permissions:
      contents: read # Allow the job to check out the repository.
    steps:
      - name: Check out the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        #
      - name: Create a draft GitHub release
        uses: rainstormy-actions/release/github@73fe3aae49ad74af650e529107d94f45002798fd # v1.1.0
        with:
          gh-auth-token: ${{ secrets.BOT_NIMBUS_GH_AUTH_TOKEN }}
          version: ${{ github.ref_name }}
