# This workflow creates a draft GitHub release from a release tag.
name: Release / Create GitHub release

on:
  push:
    tags:
      - v*

jobs:
  release-to-github:
    name: Release / Create GitHub release
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - name: Extract the version from the release tag name
        id: extract-version-from-release-tag-name
        run: |
          echo "RELEASE_VERSION=${RELEASE_TAG_NAME#v}" >> "$GITHUB_OUTPUT"
        env:
          RELEASE_TAG_NAME: ${{ github.ref_name }}
      - name: Create a draft release in GitHub
        uses: rainstormy/github-action-release-to-github@v1 # https://github.com/rainstormy/github-action-release-to-github
        with:
          gh-auth-token: ${{ secrets.BOT_NIMBUS_GH_AUTH_TOKEN }}
          release-version: ${{ steps.extract-version-from-release-tag-name.outputs.RELEASE_VERSION }}
