name: Validate

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate-types:
    name: Type checking (TypeScript)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
      - name: Install unplugged dependencies
        run: yarn install --immutable
      - name: Run the validation
        run: yarn run validate.types

  validate-lint:
    name: Static program analysis (ESLint)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
      - name: Install unplugged dependencies
        run: yarn install --immutable
      - name: Run the validation
        run: yarn run validate.lint

  validate-format:
    name: Source code formatting (Prettier)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
      - name: Install unplugged dependencies
        run: yarn install --immutable
      - name: Run the validation
        run: yarn run validate.format

  validate-unit-tests:
    name: Automated unit testing (Vitest)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
      - name: Install unplugged dependencies
        run: yarn install --immutable
      - name: Run the validation
        run: yarn run validate.test

  validate-commit-messages:
    name: Validate commit messages
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Run the validation
        uses: rainstormy/github-action-validate-commit-messages@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          rules: 'acknowledged-author-email-addresses, acknowledged-author-names, acknowledged-committer-email-addresses, acknowledged-committer-names, capitalised-subject-lines, empty-line-after-subject-lines, imperative-subject-lines, limit-length-of-body-lines, limit-length-of-subject-lines, multi-word-subject-lines, no-co-authors, no-merge-commits, no-revert-revert-commits, no-squash-commits, no-trailing-punctuation-in-subject-lines, no-unexpected-whitespace'
          acknowledged-author-email-addresses--patterns: '\d+\+.+@users\.noreply\.github\.com'
          acknowledged-author-names--patterns: '\p{Lu}.*\s.+'
          acknowledged-committer-email-addresses--patterns: '\d+\+.+@users\.noreply\.github\.com'
          acknowledged-committer-names--patterns: '\p{Lu}.*\s.+'
